---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: >-
    {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson