---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dumplings-store
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    env: "{{ .Values.global.environment }}"
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: {{ .Release.Name }}-backend
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    env: "{{ .Values.global.environment }}"